#!/bin/sh

SIGINT=2

pid=""

kill_jackup () {
    kill "$pid"
    exit
}

restart_jackup () {
	if [ "$pid" ]; then
		echo "Killing old Jackup..."
		kill "$pid"
		sleep 1
	fi
	echo "Starting Jackup"
	jackup -E none &
	pid=$!
}

trap kill_jackup $SIGINT

while true; do
    restart_jackup
    read
done
