#!/bin/sh

start_command="jackup -E none"
source_directory="lib"
check_period="1"

pid=""
lastcheckfile=".lastcheck"

kill_server () {
    kill "$pid"
    exit
}

start_server () {
    echo "Starting server..."
    $start_command &
    pid=$!
}

restart_server () {
    if [ "$pid" ]; then
        echo "Killing server $pid..."
        kill "$pid"
        sleep 1
    fi
    start_server
}

SIGINT=2
trap kill_server $SIGINT

start_server
touch "$lastcheckfile"
while true; do
    if [ $(find "$source_directory" -newer "$lastcheckfile") ]; then
        restart_server
    fi
    touch "$lastcheckfile"
    sleep "$check_period"
done
